#!/bin/sh
curl -L -o "kat-A.png" "https://new.vahy-dychl.cz/laboratorniokno1.PNG" --user-agent "Mozilla/5.0"
curl -L -o "kat-B.png" "https://new.vahy-dychl.cz/obchodnibeztiskokno1.PNG" --user-agent "Mozilla/5.0"
curl -L -o "kat-C.png" "https://new.vahy-dychl.cz/obchodnitiskokno1.PNG" --user-agent "Mozilla/5.0"
curl -L -o "kat-D.png" "https://new.vahy-dychl.cz/skladyokno1.PNG" --user-agent "Mozilla/5.0"
curl -L -o "kat-E.png" "https://new.vahy-dychl.cz/pocitaciokno1.PNG" --user-agent "Mozilla/5.0"
curl -L -o "kat-F.png" "https://new.vahy-dychl.cz/jeraboveokno1.PNG" --user-agent "Mozilla/5.0"
curl -L -o "kat-G.png" "https://new.vahy-dychl.cz/mustkoveokno1.PNG" --user-agent "Mozilla/5.0"
curl -L -o "kat-H.png" "https://new.vahy-dychl.cz/paletoveokno1.PNG" --user-agent "Mozilla/5.0"
curl -L -o "kat-I.png" "https://new.vahy-dychl.cz/silnicniokno1.PNG" --user-agent "Mozilla/5.0"
curl -L -o "kat-J.png" "https://new.vahy-dychl.cz/zdravotniokno.PNG" --user-agent "Mozilla/5.0"
curl -L -o "kat-K.png" "https://new.vahy-dychl.cz/indikatoryokno1.PNG" --user-agent "Mozilla/5.0"
curl -L -o "kat-L.png" "https://new.vahy-dychl.cz/prislusenstviokno1.PNG" --user-agent "Mozilla/5.0"
echo "Hotovo! Zkontroluj složku kategorie."
